export const ROLES = {
  JEFE_LABORATORIO: "jefe_laboratorio",
  ADMIN: "admin",
  GERENTE: "gerente",
  LOGISTICA: "logistica",
  QA: "qa",
  TECNICO_LABORATORIO: "tecnico_laboratorio",
  TECNICO_TERRENO: "tecnico_terreno"
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard:view",
  PERSONAL_DASHBOARD_VIEW: "personal-dashboard:view",
  OS_VIEW: "os:view",
  MY_OS_VIEW: "my-os:view",
  OS_CREATE: "os:create",
  REQUEST_CREATE: "request:create",
  WITHDRAWAL_ASSIGN: "withdrawal:assign",
  ASSET_MANAGE: "asset:manage",
  OS_UPDATE: "os:update",
  EQUIPOS_VIEW: "equipos:view",
  EQUIPMENT_SCAN_VIEW: "equipment-scan:view",
  EQUIPMENT_SCAN_WRITE: "equipment-scan:write",
  LAB_VIEW: "lab:view",
  LAB_EQUIPMENT_VIEW: "lab-equipment:view",
  LAB_WRITE: "lab:write",
  LAB_ASSIGN: "lab:assign",
  LAB_DISPATCH: "lab:dispatch",
  QA_VIEW: "qa:view",
  QA_SUMMARY_VIEW: "qa-summary:view",
  QA_WRITE: "qa:write",
  BODEGA_VIEW: "bodega:view",
  BODEGA_OPERATIONS_VIEW: "bodega-operations:view",
  BODEGA_WRITE: "bodega:write",
  USERS_VIEW: "users:view",
  USERS_WRITE: "users:write",
  REPORTS_VIEW: "reports:view",
  TRACE_VIEW: "trace:view",
  AI_VIEW: "ai:view",
  DISPATCH_VIEW: "dispatch:view",
  DISPATCH_OPERATIONS_VIEW: "dispatch-operations:view",
  DISPATCH_WRITE: "dispatch:write",
  BRIDGE_FLOW_VIEW: "bridge-flow:view",
  BRIDGE_WORKSPACE_VIEW: "bridge-workspace:view",
  SETTINGS_VIEW: "settings:view",
  OWN_PASSWORD_UPDATE: "own-password:update"
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export type RbacUser = {
  rol?: string | null;
  roles?: string[] | null;
} | null | undefined;

const ROLE_PERMISSIONS: Readonly<Record<Role, ReadonlySet<Permission>>> = {
  [ROLES.ADMIN]: new Set([
    PERMISSIONS.DASHBOARD_VIEW,PERMISSIONS.OS_VIEW,PERMISSIONS.EQUIPOS_VIEW,
    PERMISSIONS.EQUIPMENT_SCAN_VIEW,PERMISSIONS.LAB_VIEW,PERMISSIONS.LAB_EQUIPMENT_VIEW,
    PERMISSIONS.QA_VIEW,PERMISSIONS.QA_SUMMARY_VIEW,PERMISSIONS.BODEGA_VIEW,
    PERMISSIONS.USERS_VIEW,PERMISSIONS.USERS_WRITE,PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.TRACE_VIEW,PERMISSIONS.AI_VIEW,PERMISSIONS.BRIDGE_FLOW_VIEW,
    PERMISSIONS.BRIDGE_WORKSPACE_VIEW,PERMISSIONS.SETTINGS_VIEW,PERMISSIONS.OWN_PASSWORD_UPDATE
  ]),
  [ROLES.GERENTE]: new Set([
    PERMISSIONS.DASHBOARD_VIEW,PERMISSIONS.OS_VIEW,PERMISSIONS.EQUIPOS_VIEW,
    PERMISSIONS.EQUIPMENT_SCAN_VIEW,PERMISSIONS.LAB_VIEW,PERMISSIONS.QA_VIEW,
    PERMISSIONS.QA_SUMMARY_VIEW,PERMISSIONS.BODEGA_VIEW,PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.TRACE_VIEW,PERMISSIONS.AI_VIEW,PERMISSIONS.DISPATCH_VIEW,PERMISSIONS.BRIDGE_FLOW_VIEW
  ]),
  [ROLES.JEFE_LABORATORIO]: new Set([
    PERMISSIONS.DASHBOARD_VIEW,PERMISSIONS.LAB_VIEW,PERMISSIONS.LAB_EQUIPMENT_VIEW,
    PERMISSIONS.LAB_ASSIGN,PERMISSIONS.LAB_DISPATCH,PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.EQUIPMENT_SCAN_VIEW,PERMISSIONS.EQUIPMENT_SCAN_WRITE,PERMISSIONS.TRACE_VIEW,
    PERMISSIONS.DISPATCH_OPERATIONS_VIEW,PERMISSIONS.SETTINGS_VIEW,PERMISSIONS.OWN_PASSWORD_UPDATE
  ]),
  [ROLES.LOGISTICA]: new Set([
    PERMISSIONS.WITHDRAWAL_ASSIGN,
    PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EQUIPOS_VIEW,
    PERMISSIONS.EQUIPMENT_SCAN_VIEW,
    PERMISSIONS.EQUIPMENT_SCAN_WRITE,
    PERMISSIONS.BODEGA_VIEW,
    PERMISSIONS.BODEGA_OPERATIONS_VIEW,
    PERMISSIONS.BODEGA_WRITE,
    PERMISSIONS.BRIDGE_FLOW_VIEW,
    PERMISSIONS.TRACE_VIEW,
    PERMISSIONS.BRIDGE_WORKSPACE_VIEW,
    PERMISSIONS.TRACE_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.OWN_PASSWORD_UPDATE
  ]),
  [ROLES.QA]: new Set([
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PERSONAL_DASHBOARD_VIEW,
    PERMISSIONS.QA_VIEW,
    PERMISSIONS.QA_WRITE,
    PERMISSIONS.QA_SUMMARY_VIEW,
    PERMISSIONS.EQUIPMENT_SCAN_VIEW,
    PERMISSIONS.EQUIPMENT_SCAN_WRITE,
    PERMISSIONS.BRIDGE_FLOW_VIEW,
    PERMISSIONS.TRACE_VIEW,
    PERMISSIONS.BRIDGE_WORKSPACE_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.OWN_PASSWORD_UPDATE
  ]),
  [ROLES.TECNICO_LABORATORIO]: new Set([
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PERSONAL_DASHBOARD_VIEW,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.LAB_EQUIPMENT_VIEW,
    PERMISSIONS.LAB_WRITE,
    PERMISSIONS.BRIDGE_FLOW_VIEW,
    PERMISSIONS.TRACE_VIEW,
    PERMISSIONS.BRIDGE_WORKSPACE_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.OWN_PASSWORD_UPDATE
  ]),
  [ROLES.TECNICO_TERRENO]: new Set([
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PERSONAL_DASHBOARD_VIEW,
    PERMISSIONS.MY_OS_VIEW,
    PERMISSIONS.OS_CREATE,
    PERMISSIONS.OS_UPDATE,
    PERMISSIONS.BRIDGE_FLOW_VIEW,
    PERMISSIONS.TRACE_VIEW,
    PERMISSIONS.BRIDGE_WORKSPACE_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.OWN_PASSWORD_UPDATE
  ])
};

export function isOfficialRole(value: unknown): value is Role {
  return typeof value === "string" && Object.values(ROLES).includes(value as Role);
}

export function getUserRole(user: RbacUser): Role | null {
  const candidate = user?.rol ?? user?.roles?.[0];
  return isOfficialRole(candidate) ? candidate : null;
}

export function hasPermission(user: RbacUser, permission: Permission): boolean {
  const role = getUserRole(user);
  return role ? ROLE_PERMISSIONS[role].has(permission) : false;
}

export const can = hasPermission;

export function isReadOnlyRole(user: RbacUser): boolean {
  return getUserRole(user) === ROLES.GERENTE;
}

export function getPermissionsForRole(role: unknown): readonly Permission[] {
  return isOfficialRole(role) ? [...ROLE_PERMISSIONS[role]] : [];
}
