// Only a disposable PostgreSQL cluster; habitual database is fingerprinted through a read-only connection.
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pool,backend,root,sourceEnv,fingerprint,sequences,sourceUrl} from '../tools/database-tools.mjs';
import {emptyFixtureDatabase} from '../tools/ephemeral-postgres.mjs';
const source=pool(sourceUrl(),true),report={checks:[],passed:false};let fixture,db,server;
try{
 const before=await fingerprint(source),seq=await sequences(source);
 fixture=await emptyFixtureDatabase();assert.notEqual(fixture.port,5432);
 Object.assign(process.env,sourceEnv(),{DATABASE_URL:fixture.url});process.chdir(backend);
 const {default:app}=await import('../src/app.js');db=(await import('../src/db.js')).pool;
 const users=(await db.query('SELECT * FROM pmp.usuarios')).rows,user=role=>users.find(u=>u.rol===role);
 for(const layer of app._router.stack)for(const m of layer.handle?.stack||[])if(m.handle?.name==='firebaseAuthMiddleware')m.handle=(req,res,next)=>{const u=user(req.get('x-fixture-role'));if(!u)return res.status(401).json({error:'Isolated identity missing'});req.firebase={uid:u.firebase_uid,email:u.correo};next();};
 server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const call=async(role,method,path,body,status=200)=>{const r=await fetch(base+path,{method,headers:{'x-fixture-role':role,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();assert.equal(r.status,status,path+' '+JSON.stringify(data));return data;};
 const get=(path,role='admin')=>call(role,'GET',path);
 const summary=()=>get('/api/dashboard/executive'),reception=(query='')=>get('/api/lab/reception'+query);
 assert.equal((await summary()).assets.total,0);assert.equal((await summary()).orders.activas,0);assert.equal((await reception()).total,0);
 for(const role of ['logistica','tecnico_terreno','tecnico_laboratorio','qa'])for(const path of ['/api/dashboard/executive','/api/lab/reception'])await call(role,'GET',path,undefined,403);
 await get('/api/lab/reception','gerente');await get('/api/dashboard/executive','gerente');await call('missing','GET','/api/lab/reception',undefined,401);
 for(const query of ['?tab=invalid','?limit=0','?offset=-1','?tipo=OTRO'])await call('admin','GET','/api/lab/reception'+query,undefined,422);
 report.checks.push('Cero activos/OS, filtros validados, autorización real de todos los roles');
 const serie='7490888',asset={tipo_equipo:'VALIDADOR',serie};
 await call('logistica','POST','/api/activos',{...asset,origen:'Fixture aislado',fecha_ingreso:'2026-10-08'},201);
 const initial=await call('logistica','POST','/api/activos/recepcion/validar',{...asset,codigo:serie,origen_captura:'MANUAL_AUTORIZADO',presencia_fisica_confirmada:true});
 await call('logistica','POST','/api/activos/recepcion',{...asset,validacion_id:initial.validacion.id,validacion_inicial_conforme:true},201);
 let snapshot=await summary();assert.equal(snapshot.assets.total,1);assert.equal(snapshot.assets.disponibles,1);assert.equal(snapshot.orders.activas,0);assert.equal(snapshot.distribution.reduce((n,x)=>n+x.total,0),1);
 report.checks.push('Stock inicial sin OS: un activo disponible, cero órdenes');
 // Separate warehouse fixture; no real serial or OS is inserted or altered.
 const series='7490889';await db.query("INSERT INTO pmp.validadores(serie,modelo,marca) VALUES($1,'CVB45','Mikroelektronika')",[series]);
 const order=(await db.query("INSERT INTO pmp.ordenes_servicio(tipo_equipo,validador_serie,falla,estado_id,ubicacion_id,bus_ppu,terminal_id,pst_codigo,fecha) VALUES('VALIDADOR',$1,'Falla QR',3,1,'BJ2149',1,'U15',now()-interval '10 days') RETURNING codigo_os",[series])).rows[0].codigo_os;
 const row=async()=>(await db.query('SELECT * FROM pmp.ordenes_servicio WHERE codigo_os=$1',[order])).rows[0];
 const manual={codigo_os:order,tipo_equipo:'VALIDADOR',codigo:series,origen_captura:'MANUAL_AUTORIZADO',presencia_fisica_confirmada:true,motivo:'Ensayo aislado de recepción'};
 const dispatch=async()=>{const ev=await call('logistica','POST','/api/bodega/dispatch-lab/validar',manual);await call('logistica','PUT','/api/bodega/dispatch-lab',{codigo_os:order,validacion_id:ev.validacion.id});return ev;};
 await call('jefe_laboratorio','GET','/api/lab/custody/'+order,undefined,403);
 const exit=await dispatch();assert.equal((await row()).estado_id,2);
 const queued=await reception();assert.equal(queued.counts.camino,1);assert.equal(queued.counts.pendientes,0);assert.equal(queued.items[0].codigo_os,order);assert.equal(queued.items[0].fecha_recepcion,null);
 snapshot=await summary();assert.equal(snapshot.lab.camino,1);assert.equal(snapshot.lab.recibidos,0);assert.deepEqual(snapshot.labWorkload,[]);assert.equal(snapshot.assets.total,2);assert.equal(snapshot.orders.activas,1);assert.equal(snapshot.distribution.reduce((n,x)=>n+x.total,0),2);
 assert.equal((await reception('?q='+order)).total,1);assert.equal((await reception('?q='+series)).total,1);assert.equal((await reception('?tipo=CONSOLA')).total,0);
 await call('jefe_laboratorio','PUT','/api/lab/assign',{codigo_os:order,tecnico_id:user('tecnico_laboratorio').id},409);
 assert.ok(!(await get('/api/lab/queue/VALIDADOR')).some(o=>o.codigo_os===order));
 report.checks.push('Despacho 3→2; aparece En camino; fuera de carga, tickets y SLA; asignación bloqueada');
 const path=`/api/lab/custody/${order}/RECEPCION/`;
 for(const role of ['admin','gerente','logistica','tecnico_laboratorio','qa','tecnico_terreno'])await call(role,'POST',path+'validar',manual,403);
 await call('jefe_laboratorio','POST',path+'confirmar',{validacion_id:exit.validacion.id},409);
 const beforeRead=await row();await get('/api/lab/custody/'+order,'jefe_laboratorio');await reception();assert.deepEqual(await row(),beforeRead);
 const scanner={tipo_equipo:'VALIDADOR',codigo:series,origen_captura:'SCANNER',lectura_scanner:{tipo:'KEYBOARD_WEDGE',intervalos_ms:Array(series.length).fill(10)}};
 await call('jefe_laboratorio','POST',path+'validar',{...scanner,lectura_scanner:undefined},422);
 const discrepancy=await call('jefe_laboratorio','POST',path+'validar',{...scanner,codigo:'7490111'});assert.equal(discrepancy.coincide,false);assert.equal((await reception('?tab=incidencias')).total,1);
 const evidence=await call('jefe_laboratorio','POST',path+'validar',scanner);assert.equal((await reception('?tab=incidencias')).total,0);assert.deepEqual(await row(),beforeRead);
 const results=await Promise.all([1,2].map(()=>call('jefe_laboratorio','POST',path+'confirmar',{validacion_id:evidence.validacion.id})));assert.equal(results.filter(x=>x.duplicado).length,1);
 assert.equal((await row()).estado_id,4);assert.equal((await row()).ubicacion_id,2);
 let received=await reception('?tab=recibidos');assert.equal(received.counts.camino,0);assert.equal(received.counts.pendientes,1);assert.equal(received.counts.hoy,1);assert.equal((await reception('?tab=historial&hoy=1')).total,1);const arrival=received.items[0].fecha_recepcion;assert.ok(arrival);
 assert.equal((await summary()).labWorkload[0].fecha_ingreso_laboratorio,arrival);assert.notEqual(arrival,new Date((await row()).fecha).toISOString());
 await call('jefe_laboratorio','PUT','/api/lab/assign',{codigo_os:order,tecnico_id:user('tecnico_laboratorio').id});assert.equal((await reception()).counts.pendientes,0);
 const ticket=(await get('/api/lab/queue/VALIDADOR','tecnico_laboratorio')).find(o=>o.codigo_os===order);assert.equal(ticket.recepcion_laboratorio_confirmada,true);
 await get('/api/lab/work/'+order,'tecnico_laboratorio');assert.equal((await reception('?tab=recibidos')).items[0].fecha_recepcion,arrival);
 report.checks.push('Lectura/cancelación sin custodia; discrepancia; recepción 2→4 atómica/idempotente; asignación y apertura habilitadas; SLA fecha real');
 // Represent a subsequent QA-return cycle only in the ephemeral fixture.
 await db.query('UPDATE pmp.ordenes_servicio SET estado_id=3,ubicacion_id=1 WHERE codigo_os=$1',[order]);await dispatch();
 await call('jefe_laboratorio','POST',path+'confirmar',{validacion_id:evidence.validacion.id},409);
 assert.equal((await reception()).counts.camino,1);assert.equal((await summary()).labWorkload.length,0);
 const next=await call('jefe_laboratorio','POST',path+'validar',manual);await call('jefe_laboratorio','POST',path+'confirmar',{validacion_id:next.validacion.id});
 received=await reception('?tab=recibidos');assert.ok(Date.parse(received.items[0].fecha_recepcion)>Date.parse(arrival));
 assert.equal((await reception('?tab=historial')).total,2);assert.equal((await reception('?tab=historial&limit=1&offset=1')).items.length,1);assert.equal((await summary()).lab.reingresos,1);
 const audited=(await db.query("SELECT metadata FROM pmp.flujo_eventos WHERE codigo_os=$1 AND tipo='RECEPCION_LABORATORIO_CONFIRMADA' ORDER BY id DESC LIMIT 1",[order])).rows[0];assert.equal(audited.metadata.origen_captura,'MANUAL_AUTORIZADO');
 report.checks.push('Nuevo ciclo invalida evidencia anterior, contingencia auditada, historial paginado y reingreso con nueva fecha');
 const legacy=(await db.query("INSERT INTO pmp.ordenes_servicio(tipo_equipo,validador_serie,falla,estado_id,ubicacion_id,bus_ppu,terminal_id,pst_codigo,fecha) VALUES('VALIDADOR',$1,'Legacy aislado',4,2,'BJ2149',1,'U15',now()-interval '9 days') RETURNING codigo_os",[series])).rows[0];
 const legacyTicket=(await summary()).labWorkload.find(t=>t.codigo_os===legacy.codigo_os);assert.equal(legacyTicket.ingreso_legacy,true);assert.equal(legacyTicket.fecha_ingreso_laboratorio,null);
 assert.equal((await summary()).assets.total,2);assert.equal((await summary()).orders.activas,2);assert.equal((await summary()).labInsights.recurrentAssets,1);assert.equal((await summary()).labInsights.finished30Days,0);
 for(const [group,count] of [['activas',2],['cerradas',0],['fallas',2],['instalaciones',0]])assert.equal((await get('/api/os?grupo='+group)).pagination.total,count);
 report.checks.push('Legacy identificado, parque no duplica serie con varias OS, enlaces OS filtrados coherentes');
 const technical=await get(`/api/bridge/activos/VALIDADOR/${series}/historial?rol=admin&administrativo=true`,'jefe_laboratorio');assert.ok(Array.isArray(technical.intervenciones));assert.equal(technical.serie,series);for(const key of ['eventos','ordenes','casos','referencias','firebase_uid'])assert.equal(key in technical,false);
 const full=await get(`/api/bridge/activos/VALIDADOR/${series}/historial`);assert.ok(Array.isArray(full.eventos));report.checks.push('Jefatura recibe antecedentes técnicos sin auditoría administrativa; parámetros no amplían la proyección y Admin conserva historial completo');
 assert.deepEqual(await fingerprint(source),before);assert.deepEqual(await sequences(source),seq);report.originalUnchanged=true;report.passed=true;
}catch(error){report.error={message:error.message,stack:error.stack};process.exitCode=1;}finally{
 if(server){server.closeAllConnections?.();await new Promise(r=>server.close(r));}if(db)await db.end();await source.end();if(fixture){await fixture.dispose();report.ephemeralRemoved=true;}
 writeFileSync(resolve(root,'.local/pmp-verification/roles-2026-10-09/lab-e2e.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}
