// Actual Mobile components/services with in-memory Firebase, storage and native mocks.
// No real account, password, network, OS or database is accessed.
import test,{beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
import React from '../../04_Frontend/node_modules/react/index.js';
import Renderer,{act} from '../../04_Frontend/node_modules/react-test-renderer/index.js';
import ts from '../../04_Frontend/node_modules/typescript/lib/typescript.js';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const react=pathToFileURL(resolve(root,'../04_Frontend/node_modules/react/index.js')).href;
const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
const state=globalThis.__mobileSettings={};
const native=data(`import React from ${JSON.stringify(react)};const s=globalThis.__mobileSettings;
export const View='View',Text='Text',TouchableOpacity='TouchableOpacity',TextInput='TextInput',ScrollView='ScrollView',Image='Image',ActivityIndicator='ActivityIndicator',KeyboardAvoidingView='KeyboardAvoidingView',Ionicons='Ionicons',Switch='Switch',RefreshControl='RefreshControl',FlatList='FlatList',CameraView='CameraView',StatusBar='StatusBar';
export const StyleSheet={create:x=>x},Platform={get OS(){return s.platform||'ios';},select:x=>x[s.platform||'ios']||x.default},Appearance={getColorScheme:()=>s.system},useColorScheme=()=>s.system;
export const SafeAreaProvider=({children})=>children,SafeAreaView='SafeAreaView',useSafeAreaInsets=()=>({top:24,bottom:16,left:0,right:0}),useHeaderHeight=()=>88;
export const useNavigation=()=>s.navigation;
export const NavigationContainer='NavigationContainer',DefaultTheme={dark:false,colors:{}},DarkTheme={dark:true,colors:{}};
const Screen=({name,options})=>React.createElement('Route',{name,options});const Navigator=({children,screenOptions})=>React.createElement('Navigator',{screenOptions},children);export const createNativeStackNavigator=()=>({Screen,Navigator});
export const AuthProvider=({children})=>children;
export const useAuth=()=>({user:s.user,loading:false,sessionError:'',logout:async()=>{s.logouts++;if(s.logoutError)throw Error('raw logout detail');},retrySession:async()=>{}});
export const useCameraPermissions=()=>[{granted:false},async()=>({granted:false})];export const requestCameraPermissionsAsync=async()=>({granted:false}),launchCameraAsync=async()=>({canceled:true});
export const apiErrorMessage=()=> 'Error simulado';export default {get:async()=>{throw Error('Unexpected operational read');},post:async()=>{throw Error('Unexpected operational write');}};`);
const storage=data(`const s=globalThis.__mobileSettings;export default {getItem:async key=>{s.storageReads.push(key);if(s.readWait)await s.readWait;if(s.readError)throw Error('device storage');return s.stored;},setItem:async(key,value)=>{s.storageWrites.push({key,value});if(s.writeWait)await s.writeWait;if(s.writeError)throw Error('device storage');s.stored=value;}};`);
const sdk=data(`const s=globalThis.__mobileSettings;export const auth={get currentUser(){return s.firebaseUser;}};
export const EmailAuthProvider={credential:(email,password)=>({email,password})};
export const validatePassword=async(auth,password)=>{s.sdk.push({method:'policy',password});if(s.policyWait)await s.policyWait;if(s.policyError)throw {code:s.policyError};return s.policy;};
export const reauthenticateWithCredential=async(user,credential)=>{s.sdk.push({method:'reauth',user,credential});if(s.reauthWait)await s.reauthWait;if(s.reauthError)throw {code:s.reauthError};};
export const updatePassword=async(user,password)=>{s.sdk.push({method:'update',user,password});if(s.updateWait)await s.updateWait;if(s.updateError)throw {code:s.updateError};};`);
const cache=new Map();
async function compile(file){
 file=resolve(file);if(cache.has(file))return cache.get(file);
 let source=(await readFile(file,'utf8')).replace(/require\(['"][^'"]+\.png['"]\)/g,'"fixture-logo"');
 for(const m of [...source.matchAll(/from\s+['"]([^'"]+)['"]/g)]){
  const spec=m[1];let target=spec==='react'?react:spec==='@react-native-async-storage/async-storage'?storage:spec==='firebase/auth'||/services\/firebase$|^\.\/firebase$/.test(spec)?sdk:['react-native','react-native-safe-area-context','@expo/vector-icons','@react-navigation/native','@react-navigation/native-stack','@react-navigation/elements','expo-status-bar','expo-camera','expo-image-picker'].includes(spec)||/services\/api|context\/AuthContext/.test(spec)?native:null;
  if(!target){let path=resolve(dirname(file),spec);if(!path.endsWith('.js'))path+='.js';target=await compile(path);}
  source=source.replaceAll(`'${spec}'`,JSON.stringify(target));
 }
 const result=ts.transpileModule(source,{fileName:file+'.jsx',compilerOptions:{jsx:ts.JsxEmit.React,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true});
 assert.equal(result.diagnostics?.length||0,0,file);const url=data(result.outputText);cache.set(file,url);return url;
}
const load=async path=>import(await compile(resolve(root,path)));
const {SettingsScreen,ProfileScreen,AppearanceScreen,ChangePasswordScreen}=await load('src/screens/SettingsScreens.js');
const {AppearanceProvider,useAppearance,APPEARANCE_KEY}=await load('src/context/AppearanceContext.js');
const {changeOwnPassword,passwordErrorMessage}=await load('src/services/accountSecurity.js');
const {usePmpTheme}=await load('src/constants/styles.js');
const Home=(await load('src/screens/HomeScreen.js')).default;
const App=(await load('App.js')).default;
let renderer;
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
beforeEach(()=>Object.assign(state,{user:{uid:'test-user',nombre:'Persona',apellido:'De prueba',correo:'person@example.invalid',email:'person@example.invalid',rol:'tecnico_terreno',activo:true,id:'internal-secret',firebase_uid:'internal-uid',token:'hidden-token'},firebaseUser:{uid:'test-user',email:'person@example.invalid',providerData:[{providerId:'password'}]},system:'light',platform:'ios',stored:null,sdk:[],storageWrites:[],storageReads:[],logouts:0,logoutError:false,readError:false,writeError:false,readWait:null,writeWait:null,policyWait:null,reauthWait:null,updateWait:null,policyError:null,reauthError:null,updateError:null,policy:{isValid:true},listeners:{},navigation:{navigate:(...args)=>state.lastNavigation=args,addListener:(event,fn)=>{state.listeners[event]=fn;return()=>delete state.listeners[event];},goBack(){}}}));
afterEach(async()=>{if(renderer)await act(async()=>renderer.unmount());renderer=null;});
const text=n=>typeof n==='string'?n:(n.children||[]).map(text).join('');
const mount=async(Component,props={},provider=false)=>{await act(async()=>{const child=React.createElement(Component,{navigation:state.navigation,...props});renderer=Renderer.create(provider?React.createElement(AppearanceProvider,null,child):child);});return renderer.root;};
const button=(r,label)=>r.findAllByType('TouchableOpacity').find(n=>n.props.accessibilityLabel===label||text(n)===label);
const press=async(r,label)=>{const b=button(r,label);assert.ok(b,label);assert.ok(!b.props.disabled,label+' enabled');await act(async()=>b.props.onPress());};
const input=async(r,label,value)=>act(async()=>r.findAllByType('TextInput').find(n=>n.props.accessibilityLabel===label).props.onChangeText(value));
const body={expectedUid:'test-user',currentPassword:'current-test-only',newPassword:'New-test-only-9!',confirmation:'New-test-only-9!'};
const fill=async r=>{await input(r,'Contraseña actual',body.currentPassword);await input(r,'Nueva contraseña',body.newPassword);await input(r,'Confirmar nueva contraseña',body.confirmation);};
function Probe(){const appearance=useAppearance(),theme=usePmpTheme();state.appearance=appearance;return React.createElement('Probe',{scheme:appearance.scheme,ready:appearance.ready,background:theme.bg});}

test('Inicio abre Configuración y cada entrada usa navegación normal',async()=>{let r=await mount(Home);await press(r,'Configuración');assert.deepEqual(state.lastNavigation,['Settings']);await act(async()=>renderer.unmount());r=await mount(SettingsScreen);for(const [label,route] of [['Mi perfil','MyProfile'],['Apariencia','Appearance'],['Cambiar contraseña','ChangePassword']]){await press(r,label);assert.deepEqual(state.lastNavigation,[route]);}assert.equal(state.sdk.length,0);});
test('rutas de configuración existen solo con usuario autenticado; Safe Area y barra siguen el tema',async()=>{let r=await mount(App);assert.ok(r.findAllByType('Route').some(n=>n.props.name==='Settings'));assert.equal(r.findByType('StatusBar').props.style,'dark');state.user=null;await act(async()=>renderer.update(React.createElement(App)));assert.deepEqual(r.findAllByType('Route').map(n=>n.props.name),['Login']);assert.equal(state.sdk.length,0);});
test('perfil muestra datos reales de sesión y ningún identificador o token',async()=>{const r=await mount(ProfileScreen);for(const value of ['Persona','De prueba','person@example.invalid','Técnico en terreno','Activa'])assert.ok(text(r).includes(value));for(const secret of ['test-user','internal-secret','internal-uid','hidden-token'])assert.ok(!text(r).includes(secret));assert.equal(r.findAllByType('TextInput').length,0);assert.equal(state.sdk.length,0);});
test('perfil no inventa estado de cuenta si no está disponible',async()=>{delete state.user.activo;const r=await mount(ProfileScreen);assert.doesNotMatch(text(r),/Estado de cuenta/);});
test('apariencia restaura valor persistido antes de mostrar navegación',async()=>{const wait=deferred();state.stored='dark';state.readWait=wait.promise;const r=await mount(App);assert.equal(r.findAllByType('Route').length,0);await act(async()=>wait.resolve());assert.equal(r.findByType('StatusBar').props.style,'light');assert.equal(r.findByType('NavigationContainer').props.theme.dark,true);});
test('selector aplica inmediato, persiste solo el modo y sobrevive un nuevo montaje',async()=>{const r=await mount(AppearanceScreen,{},true),wait=deferred();state.writeWait=wait.promise;await act(async()=>{button(r,'Oscuro').props.onPress();});assert.equal(button(r,'Oscuro').props.accessibilityState.checked,true);assert.match(text(r),/Guardando preferencia/);assert.deepEqual(state.storageWrites,[{key:APPEARANCE_KEY,value:'dark'}]);await act(async()=>wait.resolve());assert.equal(state.stored,'dark');await act(async()=>renderer.unmount());await mount(Probe,{},true);assert.equal(state.appearance.scheme,'dark');});
test('Automático reacciona a cambios de sistema y Claro no cambia con el sistema',async()=>{await mount(Probe,{},true);assert.equal(state.appearance.scheme,'light');state.system='dark';await act(async()=>renderer.update(React.createElement(AppearanceProvider,null,React.createElement(Probe))));assert.equal(state.appearance.scheme,'dark');await act(async()=>state.appearance.select('light'));state.system='light';await act(async()=>renderer.update(React.createElement(AppearanceProvider,null,React.createElement(Probe))));state.system='dark';await act(async()=>renderer.update(React.createElement(AppearanceProvider,null,React.createElement(Probe))));assert.equal(state.appearance.scheme,'light');await act(async()=>state.appearance.select('system'));assert.equal(state.appearance.scheme,'dark');});
test('error al persistir es visible y permite reintentar sin perder el tema aplicado',async()=>{state.writeError=true;const r=await mount(AppearanceScreen,{},true);await press(r,'Oscuro');assert.match(text(r),/no se pudo guardar/);assert.equal(button(r,'Oscuro').props.accessibilityState.checked,true);assert.equal(state.stored,null);state.writeError=false;await press(r,'Oscuro');assert.doesNotMatch(text(r),/no se pudo guardar/);assert.equal(state.stored,'dark');});
test('lectura fallida o valor desconocido usa Automático sin bloquear la app',async()=>{state.readError=true;const r=await mount(AppearanceScreen,{},true);assert.match(text(r),/No se pudo leer/);assert.equal(button(r,'Automático').props.accessibilityState.checked,true);await act(async()=>renderer.unmount());state.readError=false;state.stored='unexpected';await mount(Probe,{},true);assert.equal(state.appearance.preference,'system');});
test('cerrar sesión reutiliza AuthContext; error visible sin éxito ficticio',async()=>{state.logoutError=true;const r=await mount(SettingsScreen);await press(r,'Cerrar sesión');assert.equal(state.logouts,1);assert.match(text(r),/No se pudo cerrar/);assert.doesNotMatch(text(r),/raw logout detail/);state.logoutError=false;await press(r,'Cerrar sesión');assert.equal(state.logouts,2);assert.doesNotMatch(text(r),/No se pudo cerrar/);});
test('formulario valida obligatorios y coincidencia antes de llamar Firebase',async()=>{const r=await mount(ChangePasswordScreen);await press(r,'Guardar contraseña');assert.match(text(r),/Ingresa tu contraseña actual/);assert.match(text(r),/Ingresa una nueva contraseña/);assert.match(text(r),/Confirma tu nueva contraseña/);await fill(r);await input(r,'Confirmar nueva contraseña','different');await press(r,'Guardar contraseña');assert.match(text(r),/no coinciden/);assert.equal(state.sdk.length,0);assert.equal(state.storageWrites.length,0);});
test('mostrar/ocultar es independiente y no envía datos',async()=>{const r=await mount(ChangePasswordScreen);await fill(r);await press(r,'Mostrar contraseña actual');assert.equal(r.findAllByType('TextInput')[0].props.secureTextEntry,false);assert.equal(r.findAllByType('TextInput')[1].props.secureTextEntry,true);await press(r,'Ocultar contraseña actual');assert.equal(r.findAllByType('TextInput')[0].props.secureTextEntry,true);assert.equal(state.sdk.length,0);});
test('SDK valida política vigente, reautentica y actualiza solo la cuenta de sesión',async()=>{await changeOwnPassword(body);assert.deepEqual(state.sdk.map(x=>x.method),['policy','reauth','update']);assert.equal(state.sdk[1].user,state.firebaseUser);assert.equal(state.sdk[2].user,state.firebaseUser);assert.equal(state.sdk[1].credential.email,state.user.correo);assert.equal(state.sdk[2].password,body.newPassword);assert.equal(state.storageWrites.length,0);});
test('política rechazada explica requisitos sin reautenticar ni actualizar',async()=>{state.policy={isValid:false,meetsMinPasswordLength:false,containsUppercaseLetter:false,containsNumericCharacter:false,passwordPolicy:{customStrengthOptions:{minPasswordLength:12}}};const r=await mount(ChangePasswordScreen);await fill(r);await press(r,'Guardar contraseña');assert.match(text(r),/12 caracteres.*mayúscula.*número/);assert.deepEqual(state.sdk.map(x=>x.method),['policy']);});
test('confirmación aparece solo después del éxito real simulado y borra campos',async()=>{const wait=deferred();state.updateWait=wait.promise;const r=await mount(ChangePasswordScreen);await fill(r);let pending;await act(async()=>{pending=button(r,'Guardar contraseña').props.onPress();});assert.doesNotMatch(text(r),/actualizada correctamente/);assert.ok(button(r,'Verificando y guardando…').props.disabled);await act(async()=>{wait.resolve();await pending;});assert.match(text(r),/actualizada correctamente/);assert.ok(r.findAllByType('TextInput').every(n=>n.props.value===''));assert.equal(state.sdk.filter(x=>x.method==='update').length,1);});
for(const [stage,code,expected] of [['reauth','auth/wrong-password',/actual es incorrecta/],['reauth','auth/invalid-credential',/verificar la contraseña actual/],['reauth','auth/user-token-expired',/sesión caducó/],['policy','auth/network-request-failed',/No hay conexión/],['update','auth/network-request-failed',/No hay conexión/],['update','auth/weak-password',/política de seguridad/],['reauth','auth/multi-factor-auth-required',/verificación adicional/]])test(`Firebase ${stage}/${code}: error útil, sin confirmación falsa`,async()=>{state[stage+'Error']=code;const r=await mount(ChangePasswordScreen);await fill(r);await press(r,'Guardar contraseña');assert.match(text(r),expected);assert.doesNotMatch(text(r),/actualizada correctamente/);if(stage!=='update')assert.equal(state.sdk.filter(x=>x.method==='update').length,0);assert.equal(state.storageWrites.length,0);});
test('cuenta distinta, sesión ausente y proveedor no compatible nunca se actualizan',async()=>{state.firebaseUser.uid='another';await assert.rejects(changeOwnPassword(body),{code:'pmp/session'});state.firebaseUser=null;await assert.rejects(changeOwnPassword(body),{code:'pmp/session'});state.firebaseUser={uid:'test-user',email:'person@example.invalid',providerData:[{providerId:'google.com'}]};await assert.rejects(changeOwnPassword(body),{code:'pmp/provider'});assert.equal(state.sdk.length,0);const r=await mount(ChangePasswordScreen);assert.equal(button(r,'Guardar contraseña').props.disabled,true);assert.match(text(r),/otro proveedor/);});
for(const stage of ['policy','reauth'])test(`cambio de sesión durante ${stage} bloquea updatePassword`,async()=>{const wait=deferred();state[stage+'Wait']=wait.promise;const pending=changeOwnPassword(body);await Promise.resolve();await Promise.resolve();state.firebaseUser={uid:'other',email:'other@example.invalid',providerData:[{providerId:'password'}]};wait.resolve();await assert.rejects(pending,{code:'pmp/session'});assert.equal(state.sdk.filter(x=>x.method==='update').length,0);});
test('salir de Seguridad borra el borrador; teclado usa altura real del encabezado',async()=>{const r=await mount(ChangePasswordScreen);await fill(r);assert.equal(r.findByType('KeyboardAvoidingView').props.keyboardVerticalOffset,88);await act(async()=>state.listeners.blur());assert.ok(r.findAllByType('TextInput').every(n=>n.props.value===''));assert.equal(state.sdk.length,0);});
test('doble pulsación no duplica updatePassword',async()=>{const wait=deferred();state.updateWait=wait.promise;const r=await mount(ChangePasswordScreen);await fill(r);const save=button(r,'Guardar contraseña').props.onPress;let pending;await act(async()=>{pending=save();save();});await act(async()=>{wait.resolve();await pending;});assert.equal(state.sdk.filter(x=>x.method==='update').length,1);});
test('tema guardado se conserva al volver al login, también en StatusBar y Safe Area',async()=>{state.stored='dark';const r=await mount(App);state.user=null;await act(async()=>renderer.update(React.createElement(App)));assert.deepEqual(r.findAllByType('Route').map(n=>n.props.name),['Login']);assert.equal(r.findByType('StatusBar').props.style,'light');assert.equal(r.findByType('NavigationContainer').props.theme.dark,true);assert.equal(r.findByType('SafeAreaView').props.style.backgroundColor,'#07111C');assert.equal(state.storageWrites.length,0);});
test('errores desconocidos no exponen datos crudos del SDK',()=>{assert.doesNotMatch(passwordErrorMessage({code:'unknown',message:'sensitive raw detail'}),/sensitive|raw detail/);});

test('encabezados secundarios comparten flecha compacta y título completo centrado',async()=>{const r=await mount(App);const options=r.findByType('Navigator').props.screenOptions;assert.equal(options.headerBackButtonDisplayMode,'minimal');assert.equal(options.headerTitleAlign,'center');for(const [route,title] of [['Settings','Configuración'],['MyProfile','Mi perfil'],['Appearance','Apariencia'],['ChangePassword','Cambiar contraseña'],['MyOrders','Mis órdenes'],['AssetHistory','Historial del activo'],['NewOrder','Reportar falla']]){const screen=r.findAllByType('Route').find(n=>n.props.name===route);assert.equal(screen.props.options.title,title);assert.equal(screen.props.options.headerBackButtonDisplayMode,undefined);}assert.deepEqual(r.findByType('SafeAreaView').props.edges,['left','right','bottom']);});
test('Inicio conserva sus tarjetas y Configuración, sin duplicar Cerrar sesión',async()=>{const r=await mount(Home);assert.ok(button(r,'Configuración'));assert.ok(button(r,'Mis órdenes'));assert.ok(button(r,'Reportar falla'));assert.ok(button(r,'Historial del activo'));assert.equal(button(r,'Cerrar sesión'),undefined);assert.equal(state.logouts,0);});
test('errores obligatorios se asocian a cada campo y se limpian individualmente',async()=>{const r=await mount(ChangePasswordScreen);await press(r,'Guardar contraseña');const fields=()=>r.findAllByType('TextInput');assert.ok(fields().every(n=>n.props.accessibilityHint));assert.equal(r.findAllByType('Text').filter(n=>n.props.accessibilityRole==='alert').length,3);await input(r,'Contraseña actual','current-test-only');assert.equal(fields()[0].props.accessibilityHint,undefined);assert.ok(fields()[1].props.accessibilityHint);assert.ok(fields()[2].props.accessibilityHint);assert.equal(state.sdk.length,0);});
test('contraseña actual incorrecta se indica junto al campo correspondiente',async()=>{state.reauthError='auth/wrong-password';const r=await mount(ChangePasswordScreen);await fill(r);await press(r,'Guardar contraseña');assert.match(r.findAllByType('TextInput')[0].props.accessibilityHint,/actual es incorrecta/);assert.equal(r.findAllByType('TextInput')[1].props.accessibilityHint,undefined);assert.equal(state.sdk.filter(x=>x.method==='update').length,0);});
test('política vigente rechazada se asocia solo a nueva contraseña',async()=>{state.policy={isValid:false,meetsMinPasswordLength:false,passwordPolicy:{customStrengthOptions:{minPasswordLength:12}}};const r=await mount(ChangePasswordScreen);await fill(r);await press(r,'Guardar contraseña');assert.match(r.findAllByType('TextInput')[1].props.accessibilityHint,/12 caracteres/);assert.equal(r.findAllByType('TextInput')[0].props.accessibilityHint,undefined);assert.deepEqual(state.sdk.map(x=>x.method),['policy']);});
test('cambiar nueva contraseña exige volver a coincidir antes del envío',async()=>{const r=await mount(ChangePasswordScreen);await fill(r);await input(r,'Nueva contraseña','Different-test-9!');await press(r,'Guardar contraseña');assert.match(r.findAllByType('TextInput')[2].props.accessibilityHint,/no coinciden/);assert.equal(state.sdk.length,0);await input(r,'Confirmar nueva contraseña','Different-test-9!');await press(r,'Guardar contraseña');assert.match(text(r),/actualizada correctamente/);assert.equal(state.sdk.filter(x=>x.method==='update').length,1);});
test('errores se limpian al abandonar pantalla; teclado mantiene scroll y acciones táctiles',async()=>{const r=await mount(ChangePasswordScreen);await press(r,'Guardar contraseña');await act(async()=>state.listeners.blur());assert.ok(r.findAllByType('TextInput').every(n=>!n.props.accessibilityHint));assert.equal(r.findByType('ScrollView').props.keyboardShouldPersistTaps,'handled');assert.equal(r.findByType('KeyboardAvoidingView').props.behavior,'padding');for(const b of r.findAllByType('TouchableOpacity').filter(n=>n.props.accessibilityLabel?.startsWith('Mostrar')))assert.ok(b.props.style.minHeight>=44);});

test('Android conserva encabezado compacto y compensación de teclado nativa',async()=>{state.platform='android';let r=await mount(App);assert.equal(r.findByType('Navigator').props.screenOptions.headerBackButtonDisplayMode,'minimal');await act(async()=>renderer.unmount());r=await mount(ChangePasswordScreen);assert.equal(r.findByType('KeyboardAvoidingView').props.behavior,'height');assert.equal(r.findByType('KeyboardAvoidingView').props.keyboardVerticalOffset,0);});
for(const theme of ['light','dark'])test(`errores por campo usan token semántico en ${theme}`,async()=>{state.system=theme;const r=await mount(ChangePasswordScreen);await press(r,'Guardar contraseña');const expected=theme==='dark'?'#f4878e':'#a52430';for(const error of r.findAllByType('Text').filter(n=>n.props.accessibilityRole==='alert'))assert.equal(error.props.style.at(-1).color,expected);});
