// Isolated presentation/interaction tests. Uses the workspace's existing React test tooling.
// Every API, camera and auth operation is mocked; no service or database is contacted.
import test,{beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
import React from '../../04_Frontend/node_modules/react/index.js';
import Renderer,{act} from '../../04_Frontend/node_modules/react-test-renderer/index.js';
import ts from '../../04_Frontend/node_modules/typescript/lib/typescript.js';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const react=pathToFileURL(resolve(root,'../04_Frontend/node_modules/react/index.js')).href;
const data=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
const state=globalThis.__mobileUx={};
export const fixture={codigo_os:'IN-TEST-01',tipo_equipo:'VALIDADOR',serie:'7490999',modelo:'CVB45',marca:'Mikroelektronika',bus_ppu:'TT0001',terminal:'Terminal de prueba',operador:'Operador de prueba',tecnico_nombre:'Persona de prueba',estado_id:1,estado_nombre:'EN_RUTA',es_instalacion:true,fecha:'2026-10-08T10:00:00Z'};
const mock=data(`import React from ${JSON.stringify(react)};
const s=globalThis.__mobileUx;
export const View='View',Text='Text',TouchableOpacity='TouchableOpacity',TextInput='TextInput',Switch='Switch',ScrollView='ScrollView',Image='Image',ActivityIndicator='ActivityIndicator',RefreshControl='RefreshControl',KeyboardAvoidingView='KeyboardAvoidingView',Ionicons='Ionicons',CameraView='CameraView';
export const FlatList=({data,renderItem,ListHeaderComponent,ListEmptyComponent,...p})=>React.createElement('List',p,ListHeaderComponent,data.length?data.map((item,i)=>React.createElement(React.Fragment,{key:i},renderItem({item}))):ListEmptyComponent);
export const StyleSheet={create:x=>x},Platform={OS:'ios',select:x=>x.ios||x.default},Appearance={getColorScheme:()=>s.theme},useColorScheme=()=>s.theme;
export const useSafeAreaInsets=()=>({top:24,bottom:16,left:0,right:0});
const nav={navigate:(...a)=>s.navigation=a,goBack:()=>s.backs++,addListener:()=>()=>{}};export const useNavigation=()=>nav;
export const useAuth=()=>({user:s.user,logout:async()=>s.logouts++,login:async()=>{throw Error('Sesión de prueba sin red');}});
export const useCameraPermissions=()=>[{granted:s.camera},async()=>({granted:s.camera})];
export const requestCameraPermissionsAsync=async()=>({granted:s.camera}),launchCameraAsync=async()=>({canceled:s.cancelPhoto,assets:[{base64:'dGVzdA==',uri:'fixture-photo'}]});
export const apiErrorMessage=e=>e.message;
export default {get:async(path)=>{s.reads.push(path);if(s.error)throw Error(s.error);if(s.hold)return new Promise(()=>{});return {data:path==='/os/activos-operativos'?{items:s.assets,has_more:false}:path.includes('/historial')?s.history:path.startsWith('/requerimientos')?[]:s.orders};},post:async(path,payload)=>{s.writes.push({path,payload});if(s.error)throw {response:{data:{message:s.error}}};return {data:path.includes('validar-identidad')?{coincide:payload.codigo_leido==='7490999',encontrado:{serie:payload.codigo_leido},codigo_leido:payload.codigo_leido,metodo_validacion:payload.metodo_validacion,validacion_id:'test-only'}:{os:{codigo_os:'MV-TEST-01'}}};}};`);
const cache=new Map();
async function compile(file){
 file=resolve(file);if(cache.has(file))return cache.get(file);
 let source=(await readFile(file,'utf8')).replace(/require\(['"][^'"]+\.png['"]\)/g,'"fixture-logo"');
 for(const m of [...source.matchAll(/from\s+['"]([^'"]+)['"]/g)]){
  const spec=m[1];let target=spec==='react'?react:['react-native','react-native-safe-area-context','@expo/vector-icons','@react-navigation/native','expo-camera','expo-image-picker','@react-native-async-storage/async-storage'].includes(spec)||/services\/api|context\/AuthContext/.test(spec)?mock:null;
  if(!target){let path=resolve(dirname(file),spec);if(!path.endsWith('.js'))path+='.js';target=await compile(path);}
  source=source.replaceAll(`'${spec}'`,JSON.stringify(target));
 }
 const result=ts.transpileModule(source,{fileName:file+'.jsx',compilerOptions:{jsx:ts.JsxEmit.React,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022},reportDiagnostics:true});
 assert.equal(result.diagnostics?.length||0,0,file+': '+JSON.stringify(result.diagnostics));
 const url=data(result.outputText);cache.set(file,url);return url;
}
const load=async path=>import(await compile(resolve(root,path)));
const Home=(await load('src/screens/HomeScreen.js')).default,Orders=(await load('src/screens/MyOrdersScreen.js')).default,Request=(await load('src/screens/NewOrderScreen.js')).default,Login=(await load('src/screens/LoginScreen.js')).default,History=(await load('src/screens/AssetHistoryScreen.js')).default,Withdrawal=(await load('src/components/TerrainWithdrawalForm.js')).default;
const {colors,getGlobalStyles}=await load('src/constants/styles.js');
const {PmpButton,StatusBadge,statusLabel,AppInput}=await load('src/components/PmpUi.js');
let renderer;
beforeEach(()=>Object.assign(state,{theme:'light',user:{nombre:'Persona',apellido:'De prueba',rol:'tecnico_terreno',email:'fixture@example.invalid'},orders:[{...fixture}],assets:[{...fixture,terminal_id:9,pst_codigo:'TEST'}],history:{...fixture,estado_actual:'En operación',intervenciones:[],ordenes:[],referencias:[],eventos:[]},reads:[],writes:[],navigation:null,backs:0,logouts:0,error:'',camera:true,cancelPhoto:false,hold:false}));
afterEach(async()=>{if(renderer)await act(async()=>renderer.unmount());renderer=null;});
const text=n=>typeof n==='string'?n:(n.children||[]).map(text).join('');
const mount=async(Component,props={})=>{await act(async()=>{renderer=Renderer.create(React.createElement(Component,props));});return renderer.root;};
const button=(r,label)=>r.findAllByType('TouchableOpacity').find(n=>n.props.accessibilityLabel===label||text(n)===label);
const press=async(r,label)=>{const b=button(r,label);assert.ok(b,label);assert.ok(!b.props.disabled,label+' enabled');await act(async()=>b.props.onPress());};
const input=async(r,label,value)=>act(async()=>r.findAllByType('TextInput').find(n=>n.props.accessibilityLabel===label).props.onChangeText(value));
const flatten=s=>Object.assign({},...(Array.isArray(s)?s.flat(Infinity):[s]).filter(Boolean));

for(const theme of ['light','dark']){
 test(`${theme}: Inicio muestra nombre real, acciones y navegación sin escribir`,async()=>{state.theme=theme;const r=await mount(Home);assert.match(text(r),/Persona De prueba/);assert.doesNotMatch(text(r),/fixture@/);await press(r,'Mis órdenes');assert.deepEqual(state.navigation,['MyOrders']);await press(r,'Reportar falla');assert.deepEqual(state.navigation,['NewOrder']);await press(r,'Historial del activo');assert.deepEqual(state.navigation,['AssetHistory']);assert.equal(state.writes.length,0);});
 test(`${theme}: instalación abre, cancela y reabre sin cambios; colores diferenciados`,async()=>{state.theme=theme;const r=await mount(Orders);await press(r,'Instalar / devolver equipo');assert.match(text(r),/Instalación IN-TEST-01/);assert.notEqual(flatten(button(r,'Confirmar instalado OK').props.style).backgroundColor,flatten(button(r,'Confirmar con falla').props.style).backgroundColor);await press(r,'Cancelar');assert.equal(button(r,'Confirmar instalado OK'),undefined);await press(r,'Instalar / devolver equipo');assert.equal(state.writes.length,0);});
 test(`${theme}: vacíos y errores se distinguen; historial y pestañas accesibles`,async()=>{state.theme=theme;state.orders=[];const r=await mount(Orders);assert.match(text(r),/Sin órdenes abiertas/);await press(r,'Historial (0)');assert.match(text(r),/Sin intervenciones cerradas/);assert.equal(r.findAllByType('TouchableOpacity').filter(n=>n.props.accessibilityState?.selected).length,1);});
 test(`${theme}: formulario sin título duplicado, autocomplete y cambio de tipo intactos`,async()=>{state.theme=theme;const r=await mount(Request);assert.doesNotMatch(text(r),/Reportar falla/);await input(r,'Bus / PPU','TT');await press(r,'Buscar activos en operación');await press(r,'Seleccionar 7490999');assert.match(text(r),/Terminal de prueba/);assert.equal(r.findAllByType('TextInput').find(n=>n.props.accessibilityLabel==='Serie del activo').props.value,'7490999');await press(r,'Consola');assert.equal(r.findAllByType('TextInput').find(n=>n.props.accessibilityLabel==='Bus / PPU').props.value,'');assert.equal(state.writes.length,0);});
 test(`${theme}: login conserva campos, logo y feedback de error`,async()=>{state.theme=theme;const r=await mount(Login);await press(r,'Iniciar sesión');assert.match(text(r),/correo y contraseña/);assert.ok(r.findAllByType('TextInput').find(n=>n.props.secureTextEntry));assert.equal(state.writes.length,0);});
 test(`${theme}: historial inicial y activo sin OS`,async()=>{state.theme=theme;const r=await mount(History,{route:{params:{}}});assert.match(text(r),/Consulta el historial técnico/);await act(async()=>renderer.update(React.createElement(History,{route:{params:{serie:'7490999',tipo_equipo:'VALIDADOR'}}})));assert.match(text(r),/Sin fallas ni reparaciones registradas/);assert.equal(state.writes.length,0);});
 test(`${theme}: tokens, botón táctil y semántica`,async()=>{state.theme=theme;const s=getGlobalStyles(colors[theme]);assert.ok(s.button.minHeight>=44);assert.ok(s.input.minHeight>=44);const r=await mount(PmpButton,{title:'Guardar',disabled:true});assert.equal(button(r,'Guardar').props.accessibilityState.disabled,true);assert.equal(s.label.textTransform,undefined);});
}
test('errores de red no se presentan como lista vacía',async()=>{state.error='Sin conexión. Desliza para reintentar.';const original=console.error;console.error=()=>{};let r;try{r=await mount(Orders);}finally{console.error=original;}assert.match(text(r),/No se pudieron cargar tus órdenes/);assert.doesNotMatch(text(r),/Sin órdenes abiertas/);assert.equal(state.writes.length,0);});
test('loading se anuncia sin activar operaciones',async()=>{state.hold=true;const r=await mount(Orders);assert.equal(r.findAllByType('ActivityIndicator').length,1);assert.equal(state.writes.length,0);});
test('instalación y devolución mantienen exactamente sus payloads (API simulada)',async()=>{for(const operativo of [true,false]){const r=await mount(Orders);await press(r,'Instalar / devolver equipo');await press(r,operativo?'Confirmar instalado OK':'Confirmar con falla');assert.deepEqual(state.writes.at(-1),{path:'/os/completar-instalacion',payload:{codigo_os:'IN-TEST-01',operativo,bus_ppu:operativo?'TT0001':null}});await act(async()=>renderer.unmount());renderer=null;}});
test('pendiente de retiro navega sin modificar custodia',async()=>{state.orders=[{...fixture,es_instalacion:false,estado_nombre:'PENDIENTE_RETIRO'}];const r=await mount(Orders);await press(r,'Confirmar retiro físico hacia Bodega');assert.deepEqual(state.navigation,['TerrainWithdrawal',{codigo_os:'IN-TEST-01'}]);assert.equal(state.writes.length,0);});
for(const pod of [false,true])test(`retiro PoD=${pod}: evidencia y confirmación siguen siendo obligatorias según condición`,async()=>{const r=await mount(Withdrawal,{order:fixture,onClose(){},onSuccess(){}});assert.equal(button(r,'Confirmar retiro hacia Bodega').props.disabled,true);await press(r,'Escanear equipo');await act(async()=>r.findByType('CameraView').props.onBarcodeScanned({data:'7490999'}));assert.equal(button(r,'Confirmar retiro hacia Bodega').props.disabled,true);await press(r,pod?'Sí':'No');if(pod){assert.equal(button(r,'Confirmar retiro hacia Bodega').props.disabled,true);await press(r,'Golpe');await input(r,'Observación técnica','Daño de prueba');await press(r,'Tomar fotografía PoD');}await act(async()=>r.findByType('Switch').props.onValueChange(true));assert.equal(button(r,'Confirmar retiro hacia Bodega').props.disabled,false);assert.equal(state.writes.filter(w=>w.path.includes('confirmar-retiro')).length,0);});
test('cámara denegada ofrece contingencia y no valida identidad',async()=>{state.camera=false;const r=await mount(Withdrawal,{order:fixture,onClose(){},onSuccess(){}});await press(r,'Escanear equipo');assert.match(text(r),/No hay permiso/);assert.equal(state.writes.length,0);});
test('Inicio conserva visibilidad por rol sin agregar permisos',async()=>{for(const rol of ['admin','logistica','qa','gerente','tecnico_laboratorio']){state.user.rol=rol;const r=await mount(Home);assert.equal(button(r,'Mis órdenes'),undefined);assert.equal(button(r,'Reportar falla'),undefined);assert.ok(button(r,'Historial del activo'));await act(async()=>renderer.unmount());renderer=null;}});
test('entrada sin coincidencias y fallo de búsqueda tienen mensajes diferentes',async()=>{state.assets=[];const r=await mount(Request);await press(r,'Buscar activos en operación');assert.match(text(r),/Sin coincidencias/);state.error='No hay conexión';await press(r,'Buscar activos en operación');assert.match(text(r),/No hay conexión/);assert.doesNotMatch(text(r),/Sin coincidencias/);assert.equal(state.writes.length,0);});
test('todos los archivos Mobile se analizan como JSX sin errores de sintaxis',async()=>{for(const file of ['App.js','src/screens/TerrainWithdrawalScreen.js']){const source=await readFile(resolve(root,file),'utf8');const result=ts.transpileModule(source,{fileName:file+'.jsx',compilerOptions:{jsx:ts.JsxEmit.React,module:ts.ModuleKind.ESNext},reportDiagnostics:true});assert.equal(result.diagnostics?.length||0,0,file);}});
test('estados legibles sin modificar códigos de entrada',async()=>{assert.equal(statusLabel('PENDIENTE_RETIRO'),'Pendiente de retiro');assert.equal(statusLabel('EN_RUTA'),'En ruta');const r=await mount(StatusBadge,{status:'CERRADO'});assert.equal(text(r),'Cerrado');});
test('input enfocado conserva acento PMP aunque reciba estilos de pantalla',async()=>{state.theme='dark';const r=await mount(AppInput,{label:'Serie',value:'',style:getGlobalStyles(colors.dark).input});await act(async()=>r.findByType('TextInput').props.onFocus({}));assert.equal(flatten(r.findByType('TextInput').props.style).borderColor,colors.dark.link);await act(async()=>r.findByType('TextInput').props.onBlur({}));assert.equal(flatten(r.findByType('TextInput').props.style).borderColor,colors.dark.border);});
test('contraste de textos y tonos PMP en claro y oscuro >= 4.5:1',()=>{
 const rgb=v=>v.startsWith('#')?[1,3,5].map(i=>parseInt(v.slice(i,i+2),16)):v.match(/[\d.]+/g).map(Number);
 const lum=v=>v.slice(0,3).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;}).reduce((a,x,i)=>a+x*[.2126,.7152,.0722][i],0);
 for(const t of [colors.light,colors.dark])for(const [name,fg,bg] of [['text',t.text,t.card],['muted',t.muted,t.card],...Object.entries(t.tones).map(([k,v])=>[k,v.text,v.bg])]){let b=rgb(bg);if(b.length===4)b=b.slice(0,3).map((v,i)=>v*b[3]+rgb(t.card)[i]*(1-b[3]));const l=[lum(rgb(fg)),lum(b)].sort((a,b)=>a-b);assert.ok((l[1]+.05)/(l[0]+.05)>=4.5,`${t.isDark}:${name}`);}
});

test('Terreno agrupa trabajo técnico, excluye auditoría y no consulta casos',async()=>{state.history={...state.history,intervenciones:[{codigo_os:'MV-TEST-02',fecha:'2026-10-08',falla_reportada:'No lee QR',diagnostico:'Lector dañado',trabajo_realizado:'Ajuste del lector',resultado:'Reparado',pendiente:false,observaciones:['Lectura verificada']}],eventos:[{tipo:'MANUAL_AUTORIZADO',comentario:'INTERNAL_SECRET'}]};const r=await mount(History,{route:{params:{serie:'7490999',tipo_equipo:'VALIDADOR'}}});for(const expected of ['MV-TEST-02','No lee QR','Lector dañado','Ajuste del lector','Reparado','Lectura verificada'])assert.match(text(r),new RegExp(expected));assert.doesNotMatch(text(r),/INTERNAL_SECRET|MANUAL_AUTORIZADO|Eventos|Referencias externas/);assert.equal(r.findAllByType('Image').length,0);assert.ok(state.reads.every(path=>!path.startsWith('/requerimientos')));assert.equal(state.writes.length,0);});
test('Terreno rechaza respuesta administrativa antigua en lugar de mostrar vacío falso',async()=>{delete state.history.intervenciones;const r=await mount(History,{route:{params:{serie:'7490999',tipo_equipo:'VALIDADOR'}}});assert.match(text(r),/No se pudo consultar el historial/);assert.doesNotMatch(text(r),/Sin fallas ni reparaciones registradas|Intervenciones \/ OS PMP/);});
test('ruta de caso no permite abrir historial administrativo para Terreno',async()=>{const r=await mount(History,{route:{params:{caso_id:'fixture-only'}}});assert.equal(state.reads.length,0);assert.match(text(r),/Consulta el historial técnico/);});
test('otros roles conservan vista histórica completa',async()=>{state.user.rol='admin';const r=await mount(History,{route:{params:{serie:'7490999',tipo_equipo:'VALIDADOR'}}});assert.match(text(r),/Intervenciones \/ OS PMP|Referencias externas|Eventos/);});
for(const result of [null,'NFF confirmado','Rechazado'])test(`resultado técnico ${result} no inventa trabajo ni éxito`,async()=>{state.history.intervenciones=[{codigo_os:'MV-TEST-03',resultado:result,pendiente:!result,observaciones:result==='Rechazado'?['Falla persiste']:[]}];const r=await mount(History,{route:{params:{serie:'7490999',tipo_equipo:'VALIDADOR'}}});assert.match(text(r),new RegExp(result||'Pendiente'));assert.doesNotMatch(text(r),/Reparado/);if(!result)assert.match(text(r),/Pendiente de diagnóstico/);if(result==='Rechazado')assert.match(text(r),/Falla persiste/);});
test('buscar referencia desde Terreno usa únicamente buscador de activos seguro',async()=>{state.orders=[fixture];const r=await mount(History,{route:{params:{}}});await input(r,'Serie, OS PMP u OS Aranda','AR-TEST-01');await press(r,'Buscar historial');assert.ok(state.reads.includes('/bridge/buscar'));assert.ok(state.reads.some(path=>path.endsWith('/historial')));assert.ok(state.reads.every(path=>!path.startsWith('/requerimientos')));assert.equal(state.writes.length,0);});
